### ISSUE TITLE
Flow for navigation

### ISSUE THREAD

**Issue by traineratoss** [traineratoss/AIMSClient2023#25]
The current route should ALWAYS be reflected in the navigation buttons. Therefore, if the route is access from a confirmation dialog (see https://github.com/traineratoss/AIMSClient2023/issues/19 ), the My Ideas or All Ideas should be selected

**Comment by MihaiV0** [comment]
this commit fixed the issue d7a87ae2f5b37d1b4b8db560377cea976782020c
